### ISSUE TITLE
bug on trim_right an empty string

### ISSUE THREAD

**Issue by cl20vv** [stephenmathieson/trim.c#3]
char *
trim_right(char *str) {
  int len = strlen(str);
  char *cur = str + len - 1;

  while (cur != str && isspace(*cur)) --cur;
  cur[isspace(*cur) ? 0 : 1] = '\0';

  return str;
}

str[] = "";
trim_right(str)
{
   len = 0;
   cur = str - 1;
   while(cur will never eq to str && suppose isspace(*cur) is true) --cur; // when buffer before str is space filled, 
    crash at random
}

**Comment by stephenmathieson** [comment]
@cl20vv i'm not able to reproduce a crash.  see 298637e and https://travis-ci.org/stephenmathieson/trim.c/builds/71303323.  can you provide more information?

**Comment by ghost** [comment]
```
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

struct membuf
{
    char buf[1];
    char str[1];
};
char * trim_right(char *str) {
    int len = strlen(str);
    char *cur = str + len - 1;

    while (cur != str && isspace(*cur)) --cur;
    cur[isspace(*cur) ? 0 : 1] = '\0';

    return str;
}

int main(void)
{
    struct membuf mb; 

    mb.buf[0] = ' ';
    mb.str[0] = '\0';

    trim_right(mb.str);

    if (mb.buf[0] != ' ')
    {   
        printf("mb.buf has been overwrite!!\n");
        abort();
    }   

    return 0;
}
```

**Comment by ghost** [comment]
@stephenmathieson , by the way, I love your describe macro, but i got some problem about it.

``` c
describe("trim_left", {
 it("should handle empty strings", {
    char str[] = {1,1}; 
    .....
 });
.....
```

error: macro "it" passed 3 arguments, but takes just 2

why couldn't use {1,1}?
